### ISSUE TITLE
JLCPB rearranged some parts

### ISSUE THREAD

**Issue by wegrei** [stuartpittaway/diyBMSv4#103] opened 2021-11-28 09:42 UTC
Hi Stuart,

first thanks for all the work you have done for the community. I follow your channel since a while as I am working on a solar power wall for my house. Have collected 2500 18650 cells so far. Now I am ready to build the first bank. Did modify your 4.40 module a bit as I am working with an external Pt resistor. Skipped the break away design for my module and rearanged the Power1 receptable a bit (makes it easier for my snap in mounting). Worked all fine. Did send the gerbers, BOM and CPL to China. They have reviewed the module and changed the orientation of D2 on the board (see picture attached). Is that right?
They also rearranged some parts on the controller board. In the DFM Analysis I got a warning that PAD to PAD spacing is too large. I think I can skip that warning. Then they changed orientation of D1. This is in order with the marking on the boeard. Is that correct? Furtheron they turned the SD-Card around, which I think is the bigger problem as the screen is covering the slot then. Is there a problem in the design or did they make a mistake there. Would be nice if you could help me out.
Again thanks a lot, greetings from Germany, Wern
![DFM Analysis Cell Module](https://user-images.githubusercontent.com/77070559/143762981-448e08b2-7984-46ac-bdb7-a9fd9de36a2c.JPG)
![DFM Analysis Controller Board](https://user-images.githubusercontent.com/77070559/143762984-c0ce2afa-adbf-4cc7-9746-49a837a5caf4.JPG)
er

**Comment by stuartpittaway** [comment] 2021-11-28 10:58
Normally jlc know what they are doing, so it's likely ok to go with the changes.

The problem is that they keep restocking parts and at the same time change the orientation, so I. Can't keep up with their changes.

**Comment by wegrei** [comment] 2021-11-28 14:24
Thanks Stuart,

that helps. Lets wait and see what shows up.

Have a good one, Werner

**Comment by wegrei** [comment] 2021-12-12 14:20
Hi Stuart,

just received the printed boards from china. There really seem to be a problem in the design. As it looks like the SD card has to be turned by 180°, as JLPCB did. Then you can not access the card anymore as the slot is pointing inwards. Doublechecked with the datasheet, the circuit and the printed layout. Seems that the layout has to be turned by 180°. Pls check if I am right. I might have to order a new set then.

Thanks

Werne
![circuit board 01](https://user-images.githubusercontent.com/77070559/145716183-f5f4f961-e8cb-4701-9743-c613236d9a72.jpg)
![circuit board 02](https://user-images.githubusercontent.com/77070559/145716187-30ce9c41-95ff-449f-8304-c1748f602d50.jpg)
![SD-Card Holder](https://user-images.githubusercontent.com/77070559/145716189-d5e2248c-ca2b-4f37-abdd-835acd3b255a.JPG)
![SD-Card Holder circuit board](https://user-images.githubusercontent.com/77070559/145716191-d0f7783f-28b6-4764-92c3-a4eb37ffbfcf.JPG)
r

**Comment by stuartpittaway** [comment] 2021-12-12 15:38
Did you notice that the card slot is the same as used in some old mobile phones? You slide the metal cover up and the card does inside. It doesn't push in from the side.

The PCB was changed to use this part about a year ago, so jlc could assemble it. The notch on the PCB for the card was also removed at that time.

**Comment by wegrei** [comment] 2021-12-12 17:22
Thanks Stuart,

the holder JLPCB mount is a fixed one (slide in from the side). However try to buy one which can be slided up. It still will be hard to get access to the card as the screen is mounted above. I have to mount the screen then with a noticable distance to the board to make it happen. Anyhow I will get it fixed.

Thanks again and have a good day

Werner

**Comment by stuartpittaway** [comment] 2021-12-12 17:26
The photo above is not a fixed one. You slide open the locking tab on the top.

The card isn't designed to be regularly removed, so no problem with the TFT screen above.

**Comment by wegrei** [comment] 2021-12-12 17:31
Oughh,

now I see. You are right I can slip / flip it open. Then it works for sure. Sorry for all the stupid questions and the confusion. Again thanks for your help.

Werner

**Closed** 2021-12-13 11:26 UTC
